### ISSUE TITLE
step functions plugin - original lambda input lost after exception

### ISSUE THREAD

**Issue by jraj002** [serverless-operations/serverless-step-functions#318]
Hi,

I am running into an issue in my step function where I am losing the original input if an exception is thrown within any Lambda. I do have a catchall for all the lambdas and I am adding the exception to the 'error' path. However, the input to the lambda function does not carry through to the catchall lambda function.
```
  Catch:
              - ErrorEquals: ["States.ALL"]
                Next: NotifyError
                ResultPath: "$.error"
```

**Additional Data**

Serverless Framework Core Version you're using:
Your Environment Information ---------------------------
Operating System: darwin
Node Version: 12.1.0
Framework Version: 1.56.1
Plugin Version: 3.2.1
SDK Version: 2.1.2
Components Core Version: 1.1.2
Components CLI Version: 1.4.0

The Plugin Version you're using:

Operating System:
MacOS 10.14.6
