### ISSUE TITLE
Bug:  Override Step Functions Role Not Working

### ISSUE THREAD

**Issue by andrewjroth** [serverless-operations/serverless-step-functions#325]
# Bug Report

## Description

* What went wrong?

I attempted to override the definition of the AWS::IAM::Role used by the Step Function State Machine to use managed policies instead of inline policies.  However, my definition of the role has the inline policy added back during deployment.  This causes an error for my environment as we don't allow inline policies.

* What did you expect should have happened?

The overridden resource (AWS::IAM::Role) should not have properties changed or added during deployment.

* What was the config you used?

```
﻿plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
[...]
﻿stepFunctions:
  stateMachines:
    myWorkflow:
      definition:
        Comment: "My Special Workflow"
        StartAt: Validate
        States:
          Validate:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-validate"
            End: true
[...]
﻿resources:
  Resources:
    MyWorkflowStepFunctionsStateMachineRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                  - states.us-east-1.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::111122223333:policy/AWSLambdaRole
```

* What stacktrace or error message from your provider did you see?

The generated ﻿`cloudformation-template-update-stack.json` contains this resource:

```
﻿    "MyWorkflowStepFunctionsStateMachineRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "states.us-east-1.amazonaws.com"
                ]
              },
              "Action": "sts:AssumeRole"
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": "dev-us-east-1-myproject-statemachine",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "lambda:InvokeFunction"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:network-tgw-manager-dev-validate"
                    },
                    {
                      "Fn::Sub": [
                        "${functionArn}:*",
                        {
                          "functionArn": {
                            "Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:network-tgw-manager-dev-validate"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          }
        ],
        "ManagedPolicyArns": [
          "arn:aws:iam::111122223333:policy/AWSLambdaRole"
        ]
      }
    },
```

The Policies section should not exist in the generated CFT.

Note that the Managed Policy (AWSLambdaRole) has all of the permissions specified in the inline policy.

## Additional Data
* ***Serverless Framework Core Version you're using***:  1.67.3
* ***The Plugin Version you're using***:  2.18.0
* ***Operating System***: linux
