### ISSUE TITLE
Unable to conditionally set properties

### ISSUE THREAD

**Issue by roni-frantchi** [serverless-operations/serverless-step-functions#339]
# This is a Bug Report

## Description
Given #334 , we wanted to conditionally enable `LoggingConfiguration` only on certain stages.  

I tried two approaches to that:  
1. First, we tried using [`serverless-plugin-ifelse`](https://www.npmjs.com/package/serverless-plugin-ifelse) like so:
    ```yml  
    custom:
      serverlessIfElse:
        - If: '["dev","prod"].includes("${self:custom.stage}")'
          Set:
            stepFunctions.stateMachines.deployment.loggingConfig:
              level: ERROR
              includeExecutionData: true
              destinations:
                - Fn::GetAtt:
                    - StepFunctionLogGroup
                    - Arn
    ```
    But it seems `serverless-step-functions` somehow manipulates the serverless template before [`serverless-plugin-ifelse`](https://www.npmjs.com/package/serverless-plugin-ifelse) has a chance to apply its conditions.  

2. Then I tried setting the `loggingConfiguration` to a CloudFormation condition function:
    ```yml
    stepFunctions:
      stateMachine:
        deployment:
                loggingConfig:
          Fn::If:
            - Fn::Or:
              - Fn::Equals:
                - 'dev'
                - ${self:custom.stage}
              - Fn::Equals:
                - 'prod'
                - ${self:custom.stage}
            - level: ERROR
              includeExecutionData: true
              destinations:
                - Fn::GetAtt:
                  - StepFunctionLogGroup
                  - Arn
            - Ref: AWS::NoValue
    ```

    That failed with:
        ```
      ValidationError: child "loggingConfig" fails because ["Fn::If" is not allowed]
        ```

## Additional Data
* ***Serverless Framework Core Version you're using***:
* ***The Plugin Version you're using***: 2.19.0
* ***Operating System***: macOS

**Comment by theburningmonk** [comment]
@roni-frantchi how about something like this?

```yml
custom:
  sfnLoggingConfig:
    default:
    prod: 
      level: ERROR
      includeExecutionData: true
      destinations: !GetAtt StepFunctionLogGroup.Arn

stepFunctions:
  stateMachine:
    deployment:
      loggingConfig: ${self:custom.sfnLoggingConfig.${self:custom.stage}, self:custom.sfnLoggingConfig.default}
      definition: ...
```

Haven't tried it myself, but it might work

**Comment by theburningmonk** [comment]
@roni-frantchi just gave it a quick test, seems to do the trick and only generates the logging config for specific stages (`prod` in this case)

**Comment by roni-frantchi** [comment]
Seems to be working!
Thanks @theburningmonk !  
Will close the issue as there's at least one valid way of achieving what's described.

**Comment by nuskirk** [comment]
Any one help me, I have a config yml: 
```yml
stepFunctions:
  stateMachines:
    provisioningEmailMachine:
      type: EXPRESS
      loggingConfig:
        level: ERROR
        includeExecutionData: true
        destinations:
          - !GetAtt lamdataFunctionLogs.Arn
```
But I have an error: **The CloudFormation template is invalid: ValidationError: Template error: instance of Fn::GetAtt references undefined resource lamdataFunctionLogs**
Can help me if I mistake something?

**Comment by nuskirk** [comment]
@theburningmonk @roni-frantchi

**Comment by GoGoris** [comment]
Unfortunately this fix doesn't work for me, `ValidationError: child "loggingConfig" fails because [child "destinations" fails because ["destinations" must be an array]]`. Possibly something changed in the validations?

**Comment by ankit-bhadja-sf** [comment]
Getting same problem with serverless 3.19.0.

```yml
stateMachine:
  name: ${self:service}-${opt:stage, self:provider.stage}-proxy-state-machine # able to access self
  definition:
    StartAt: transform
    States:
      transform:
        Type: Task
        Resource: arn:aws:lambda:us-east-2:123456789:function:${self:provider.stage}-storeMapingData # NOT able to access self
        Next: upload
      upload:
        Type: Task
        Resource: arn:aws:lambda:us-east-2:123456789:function:${self:provider.stage}-uploadImages # NOT able to access self
        Next: update-es
      update-es:
        Type: Task
        Resource: arn:aws:lambda:us-east-2:123456789:function:${self:provider.stage}-updateEs # NOT able to access self
        End: true
```

Error: 
```
Environment: linux, node 16.15.1, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "stepFunctions.stateMachines.proxy-state-machine.definition.States.transform.Resource": Value not found at "self" source,
  - Cannot resolve variable at "stepFunctions.stateMachines.proxy-state-machine.definition.States.upload.Resource": Value not found at "self" source,
  - Cannot resolve variable at "stepFunctions.stateMachines.proxy-state-machine.definition.States.update-es.Resource": Value not found at "self" source
  -
```
