### ISSUE TITLE
Is it possible to pass in a Resource as an input during execution?

### ISSUE THREAD

**Issue by SanjayS5** [serverless-operations/serverless-step-functions#340]
# Question about a possible feature

## Description

Is it possible to pass in a Resource as an input during execution?

```
GetExecutionName:
  Type: Task
  Resource: arn:aws:states:::lambda:invoke
  Parameters:
    FunctionName.$: $$.DynamicFunctionArn <-- Is this possible?
    Payload:
      ExecutionName.$: "$$.Execution.Name"
```
Example adapted from issue 209 linked below

For example, I want to be able to retry a lambda. Normally, I would have to enter the ARN of the lambda into the resource section like so "Resource: some_lambda_arn".

In my case, I will not know the lamdba ARN in advance. Instead, I will get the lambda ARN as part of the error attributes sent as part of Serverless' error destinations functionality via SQS. 

Use case: If Lambda A fails, the failure is sent to SQS -> Lambda B which triggers a state machine to retry Lambda A 

(Note: The ARN of lambda A is sent as an attribute of the failure message to SQS).

My questions i, can I pass in the ARN of Lambda A as an input to the state machine, which then uses that to set the Resource?

EDIT: Just stumbled across this [issues/209](https://github.com/serverless-operations/serverless-step-functions/issues/209) But instead of the hardcoded ARN, I want to pass in the ARN as an input variable.

**Comment by SanjayS5** [comment]
As it turns out, you can! 

```
GetExecutionName:
  Type: Task
  Resource: arn:aws:states:::lambda:invoke
  Parameters:
    FunctionName.$: $.DynamicFunctionArn
```

This is what you would do, and the reason it wasn't working for me is because I had an extra hyphen before FunctionName :) 

Can I please request that this feature be added to the documentation? Cheers.
