### ISSUE TITLE
Getting [object Object] instead of string when passing in ARN

### ISSUE THREAD

**Issue by ilrein** [serverless-operations/serverless-step-functions#345]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Getting [object Object] instead of string when passing in ARN

* What did you expect should have happened?
Expected to get a string

* What was the config you used?
```
service: shopify-reminder-service
app: shopify-reminder
org: ilrein

plugins:
  - serverless-dotenv-plugin
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: arn:aws:ses:${self:provider.region}:*:*

functions:
  createReminder:
    handler: reminders/create.index
    environment:
      statemachine_arn: ${self:resources.Outputs.sendEmailReminder.Value}
    events:
      - http:
          path: reminders
          method: post
          cors: true
  sendEmail:
    handler: reminders/email.index

stepFunctions:
  stateMachines:
    sendEmailReminderFunc:
      id: sendEmailReminder
      definition:
        Comment: "Trigger email lamdba at a specific timestamp"
        StartAt: Begin
        States:
          Begin:
            Type: Pass
            Next: ExecuteOn
          ExecuteOn:
            Type: Wait
            TimestampPath: "$.reminderDate"
            Next: Finish
          Finish:
            Type: Task
            Resource:
              Fn::GetAtt: [sendEmail, Arn]
            End: true

resources:
  Outputs:
    sendEmailReminder:
      Description: The ARN of sendEmailReminderFunc
      Value:
        Ref: sendEmailReminder
```

* What stacktrace or error message from your provider did you see?
no error

## Additional Data
* ***Serverless Framework Core Version you're using***:
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.12

* ***The Plugin Version you're using***:
"serverless-step-functions": "^2.19.0",

* ***Operating System***:
OSX

Note: I tried using both `id` and `name` -- both result in `[object Object]`
