### ISSUE TITLE
The TimestampPath parameter does not reference an input value

### ISSUE THREAD

**Issue by ilrein** [serverless-operations/serverless-step-functions#346]
# This is a Bug Report

## Description
My step function has JSON inputs, but fails to reference them (I'm probably doing something wrong but I can't seem to spot my mistake from reading the docs).

For bug reports:
* What went wrong?
Passed in a JSON body like so:
```
{
  "reminder": {
    "date": "2020-06-12T04:25:12.698Z",
    "to": "ilrein@hotmail.com",
    "from": "ilia.reingold@gmail.com",
    "subject": "hello world",
    "content": "lorem ipsum"
  }
}
```

to my step function:

```
stepFunctions:
  stateMachines:
    sendEmailReminderFunc:
      name: sendEmailReminder
      definition:
        Comment: "Trigger email lamdba at a specific timestamp"
        StartAt: Begin
        States:
          Begin:
            Type: Pass
            Next: ExecuteOn
          ExecuteOn:
            Type: Wait
            TimestampPath: "$.reminder.date"
            Next: Finish
          Finish:
            Type: Task
            Resource:
              Fn::GetAtt: [sendEmail, Arn]
            End: true
```
Note the `TimestampPath: "$.reminder.date"`

* What did you expect should have happened?
The function should read `reminder.date` successfully

* What was the config you used?
Full yaml:

```
service: shopify-reminder-service
app: shopify-reminder
org: ilrein

plugins:
  - serverless-dotenv-plugin
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: arn:aws:ses:${self:provider.region}:*:*
    - Effect: 'Allow'
      Action:
        - 'states:StartExecution'
      Resource: arn:aws:states:${self:provider.region}:*:stateMachine:sendEmailReminder

functions:
  authenticateApp:
    handler: shopify-token/authenticateApp.index
    events:
      - http:
          path: authenticate
          method: get
          cors: true
  permanentToken:
    handler: shopify-token/getPermanentToken.index
    events:
      - http:
          path: token
          method: get
          cors: true

  createReminder:
    handler: reminders/create.index
    environment:
      statemachine_arn: !Ref SendEmailReminder
    events:
      - http:
          path: reminders
          method: post
          cors: true
  sendEmail:
    handler: reminders/email.index

stepFunctions:
  stateMachines:
    sendEmailReminderFunc:
      name: sendEmailReminder
      definition:
        Comment: "Trigger email lamdba at a specific timestamp"
        StartAt: Begin
        States:
          Begin:
            Type: Pass
            Next: ExecuteOn
          ExecuteOn:
            Type: Wait
            TimestampPath: "$.reminder.date"
            Next: Finish
          Finish:
            Type: Task
            Resource:
              Fn::GetAtt: [sendEmail, Arn]
            End: true

resources:
  Outputs:
    sendEmailStateMachine:
      Description: The ARN of sendEmailReminderFunc
      Value:
        Ref: SendEmailReminder

```

And the lamdba function that calls the step function:

```
'use strict';

const AWS = require('aws-sdk');
const { tagEvent } = require('../serverless_sdk'); // eslint-disable-line

module.exports.index = (event, context, callback) => {
  tagEvent('createReminder', JSON.stringify(event.body));

  // const {
  //   date,
  //   to,
  //   from,
  //   subject,
  //   content,
  // } = event.reminder;

  const params = {
    stateMachineArn: process.env.statemachine_arn,
    input: JSON.stringify(event.body),
  };

  // initiate step function with these params next
  const stepfunctions = new AWS.StepFunctions();

  let statusCode;
  let result;

  stepfunctions.startExecution(params, (err, data) => {
    tagEvent('startExecution', JSON.stringify(err, data));
    if (err) {
      tagEvent('error startExecution()', JSON.stringify(err));
      statusCode = 500;
      result = err;

      callback(null, {
        statusCode,
        headers: {
          'Access-Control-Allow-Origin': '*', // Required for CORS support to work
          'Access-Control-Allow-Credentials': true, // Required for cookies, authorization headers with HTTPS
        },
        body: JSON.stringify(
          {
            result,
          },
          null,
          2,
        ),
      });
    } else {
      tagEvent('success startExecution()', JSON.stringify(data));
      statusCode = 200;
      result = data;

      callback(null, {
        statusCode,
        headers: {
          'Access-Control-Allow-Origin': '*', // Required for CORS support to work
          'Access-Control-Allow-Credentials': true, // Required for cookies, authorization headers with HTTPS
        },
        body: JSON.stringify(
          {
            result,
          },
          null,
          2,
        ),
      });
    }
  });
};

```

* What stacktrace or error message from your provider did you see?
```
{
  "error": "States.Runtime",
  "cause": "An error occurred while executing the state 'ExecuteOn' (entered at the event id #4). The TimestampPath parameter does not reference an input value: $.reminder.date"
}
```

The received input in the step function:

`"{\n  \"reminder\": {\n    \"date\": \"2020-06-12T04:25:12.698Z\",\n    \"to\": \"ilrein@hotmail.com\",\n    \"from\": \"ilia.reingold@gmail.com\",\n    \"subject\": \"hello world\",\n    \"content\": \"lorem ipsum\"\n  }\n}"`

## Additional Data
* ***Serverless Framework Core Version you're using***:
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.12

* ***The Plugin Version you're using***:
"serverless-step-functions": "^2.19.0",

* ***Operating System***:
OSX
