### ISSUE TITLE
useExactVersion conflicts with pseudo-parameter

### ISSUE THREAD

**Issue by bondezbond** [serverless-operations/serverless-step-functions#352]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* When I'm using pseudo-parameter plugin with step function everything works fine. But the minute I try to use exact versions it fails to deploy cause it seems like it can't validate the '#{AWS:AccountId}'

```
service: StateProcessor
frameworkVersion: ">=1.71.3 <2.0.0"

plugins:
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-plugin-log-subscription

custom:
  version: ${env:BUILD_VERSION, self:provider.stage}

provider:
  name: aws
  stage: ${opt:stage, 'dev'}

stepFunctions:
  stateMachines:
    ExpandEvent:
      useExactVersion: true
      definition:
        Comment: "State Machine"
        StartAt: EventFilter
        States:
          EventFilter:
            Type: Choice
            Choices:
              - Variable: "$.eventType"
                StringEquals: "NEED_TO_EXPAND"
                Next: Expand
            Default: IgnoreEvent
          Expand:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:#{AWS::AccountId}:function:FUNCTIONAME
.....
```

For feature proposals:
* I would think the plugin would still be able to evaluate #{AWS:AccountId} for Resource arns for lambdas. I can't use GetAtt since the lambda is in a different project.

Similar or dependent issues:
* #291 

## Additional Data
```
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.1
     Framework Version:         1.74.1
     Plugin Version:            3.6.15
     SDK Version:               2.3.1
     Components Version:        2.31.10
```
