### ISSUE TITLE
When deploying step function, newService: ${self:} causes RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dev-guy** [serverless-operations/serverless-step-functions#365]
# This is a Bug Report

## Description

Crash deploying a step function because the 'custom' section contains newService: ${self:}

## Versions

- lts/dubnium
- serverless@1.77.0
- serverless-pseudo-parameters@2.5.0
- serverless-step-functions@2.22.1

## Stack Trace

```
serverless deploy
```

```
RangeError: Maximum call stack size exceeded
      at isLength (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:11739:22)
      at isArrayLike (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:11359:31)
      at keys (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13333:14)
      at /Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:4920:21
      at baseForOwn (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:2990:24)
      at Function.mapValues (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/node_modules/lodash/lodash.js:13426:7)
      at Variables.getProperties (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/lib/classes/Variables.js:272:11)
      at addContext (/Users/justin/.nvm/versions/node/v10.21.0/lib/node_modules/serverless/lib/classes/Variables.js:262:12)
```

## How to Fix

Do not create a custom variable that evaluates to ${self:}

Use this instead:

```
custom:
  serviceName: ${self:service}
```

The word "newService" probably isn't the issue; however, I am not sure about that. The bug is probably caused by setting any custom value to the result of ${self:}. Therefore, another solution is probably the following, which is preferable since you won't have to change every usage of newService to serviceName.

```
custom:
  newService: ${self:service}
```

**Comment by theburningmonk** [comment]
@dev-guy can you provide a full example so we can repro? I don't understand what the problem is here.

**Comment by dev-guy** [comment]
```
frameworkVersion: '>=1.1.0'

service: groucho

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
package:
  # dev dependencies and .dotfiles are excluded by default
  exclude:
    - package-lock.json
    - README.md
    - serverless.yml
    - docs/**
    - logs/**
    - node_modules/**/aws-sdk/**
    - node_modules/**/README.*
    - tests/**

custom:
  # newService: ${self:} # WARNING: THIS BREAKS THE 'serverless-step-functions' PLUGIN
  serviceName: ${self:service}
  bucket: ${opt:bucket, '${self:provider.stage}-nora-science37'}

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 600 # 10 minutes. It is unclear whether this is for the lambda or the step function or both.
  functionVersions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}

  iamRoleStatements:
    # CloudWatch Logs
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:DescribeLogStreams
        - logs:PutLogEvents
      Resource:
        - 'arn:aws:logs:*:*:*'

functions:
  lambda:
    name: '${self:service}-${self:provider.stage}'
    handler: index.handler
    environment:
      NODE_ENV: ${self:provider.stage}

# Wait 5 minutes and start
stepFunctions:
  stateMachines:
    groucho:
      name: '${self:custom.serviceName}-${self:provider.stage}'
      definition:
        StartAt: Pause
        States:
          Pause:
            Type: Wait
            Seconds: 300 # 5 minutes
            Next: go
          go:
            Type: Task
            Resource:
              Fn::GetAtt: [labda, Arn]
            End: true
```
