### ISSUE TITLE
loggingConfig is not converted to cloudformation

### ISSUE THREAD

**Issue by MrAtheist** [serverless-operations/serverless-step-functions#383]
# This is a (Bug Report)

## Description

loggingConfig is not converted to cloudformation

For bug reports:
* What went wrong?

> loggingConfig is not converted to cloudformation; thus the step function didnt have logging enabled

* What did you expect should have happened?

> `loggingConfig` should be compiled as part of the cloudformation

* What was the config you used?

```
stepFunctions:
  stateMachines:
    StateMachine:
      name: StateMachine${self:provider.stage}
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [AccessLogs, Arn]
      role:
        Fn::GetAtt: [StateMachineRole, Arn]

# i can see the `RoleArn` being converted
```
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.5.1
* ***The Plugin Version you're using***: 2.21.1
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:
