### ISSUE TITLE
Step Function Parameter String Construction

### ISSUE THREAD

**Issue by yatesdev** [serverless-operations/serverless-step-functions#399]
## Description
As of Aug 2020, the step function definitions within AWS have allowed string construction within the definition.

https://aws.amazon.com/blogs/aws/aws-step-functions-adds-updates-to-choice-state-global-access-to-context-object-dynamic-timeouts-result-selection-and-intrinsic-functions-to-amazon-states-languages/

However, when attempting to use this, the plugin throws an error for invalid state machine definition. Curious if there is anything I'm doing wrong or if this is currently unsupported by serverless.

```yaml
stepFunctions:
  stateMachines:
    test:
      name: test
      definition:
        StartAt: TestTask
        States:
          TestTask:
            Type: Task
            Resource: ${arnGoesHere}
            Parameters:
              outputPath.$: States.format('test-{}.json', $.Comment)
            End: true
```

attempting to run `serverless -s dev deploy`

I get the following error:
```
Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: The value for the field 'outputPath.$' must be a valid
JSONPath or a valid intrinsic function call at /States/TestTask/Parameters'
(Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: 29c19480-fd3d-45ff-94df-68bebf1aa1c0; Proxy: null).
```

## Additional Data
* ***Serverless Framework Core Version you're using***:
* 2.19.0
* ***The Plugin Version you're using***:
* 2.29.0
