### ISSUE TITLE
Bug - Intrinsic functions in eventBusName return [object, object]

### ISSUE THREAD

**Issue by Kevchan85** [serverless-operations/serverless-step-functions#405]
# This is a Bug Report

## Description

- What went wrong?
When passing in intrinsic functions to eventbus name I got an error: Member must satisfy regular expression pattern: (arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+ 

- What did you expect should have happened?
The intrinsic function should be passed to cloud formation and it should decide dynamically what bus name to use.

- What was the config you used?
```
stepFunctions:
  validate: true
  stateMachines:
    salesProfile:
      events:
        - cloudwatchEvent:
            eventBusName:
              Fn::If:
                - isLocal
                - Fn::GetAtt: [localEventBus, Name]
                - vela-${self:custom.environment}
            event:
              source:
                - 'webApi'
```  

- What stacktrace or error message from your provider did you see?

```  
Serverless Error ---------------------------------------
 
  An error occurred: SalesProfileEventsRuleCloudWatchEvent1 - 1 validation error detected: Value '[object Object]' at 'eventBusName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+ (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: ValidationException; Request ID: c82ba63b-cb76-45e7-b7d0-2b185efefd5e; Proxy: null).
```

The expected behavior is that we just pass JSON to the cloudformaiton template and let the name resolve based on the parameters passed.
