### ISSUE TITLE
Bug - Hardcoded Region breaks single package deployment strategies

### ISSUE THREAD

**Issue by ericSpence** [serverless-operations/serverless-step-functions#407]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

When packaging a stack once and deploying the artifact to multiple regions the AssumePolicyDocument contains the wrong region value.  Looks like [iam-role-statemachine-execution-template.txt](https://github.com/serverless-operations/serverless-step-functions/blob/master/lib/iam-role-statemachine-execution-template.txt#L10) is hardcoded to use the build time region not the runtime region. We publish one artifact at build time and then use our internal build tool to propagate that through our testing and production environments. Having a single region referenced there instead of a psuedo CloudFormation  parameter breaks that

* What did you expect should have happened?

Expectation: "states.[region].amazonaws.com"
Actual: "states.${AWS::Region}.amazonaws.com"

* What was the config you used?
Happens regardless of config.

## Additional Data
An easy fix to this should be to update [iam-role-statemachine-execution-template.txt](https://github.com/serverless-operations/serverless-step-functions/blob/master/lib/iam-role-statemachine-execution-template.txt#L10) to use 
"states.${AWS::Region}.amazonaws.com" instead of hard coding the region

Current workaround: 
```
Properties:
     AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
             Principal:
             Service:
                Fn::Sub:
                  - states.${AWS::Region}.amazonaws.com
                  - {}
              Action: sts:AssumeRole
```
