### ISSUE TITLE
Latest version of plugin throws error with latest version of serverless framework

### ISSUE THREAD

**Issue by alexanderluiscampino** [serverless-operations/serverless-step-functions#409]
# Bug Report
Getting the following error:
```
Invalid variable reference syntax for variable . You can only reference env vars, options, & files. You can check our docs for more info.
```
![image](https://user-images.githubusercontent.com/32500355/109747920-d4c12e00-7b8c-11eb-9ef2-c2e4b3edae05.png)

This happens with the latest `npm install --save-dev serverless-step-functions` -> `serverless-step-functions@2.29.0`

version: `serverless-step-functions@2.19.0` does not have this issue.

```
serverless --version
Framework Core: 2.28.3
Plugin: 4.4.3
SDK: 2.3.2
Components: 3.7.1
```

## Description
 In very simple terms, this is my serverless.yml:
```yml
service: test-step-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221


plugins:
    - serverless-step-functions

functions:
  hello:
    handler: handler.hello
```

If the plugin section is commented out, the deployment goes through without a hitch. The absence of a `stepFunction` section is not a problem, nor it is needed. Simply including the plugin reference should not cause this to crash.
