### ISSUE TITLE
Config cloudWatch with serverless.yml Error

### ISSUE THREAD

**Issue by nuskirk** [serverless-operations/serverless-step-functions#414]
I follow this example about config **CloudWatchLogs**  for the **Express Workflow** 
```yml
stepFunctions:
  stateMachines:
    hellostepfunc1:
      type: EXPRESS
      loggingConfig:
        level: ERROR
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [MyLogGroup, Arn]
```
But It not clear. What is the _MyLogGroup_ and how I can config for this?
I try to create a function lambda _MyLogGroup_ and build so I have an issue: 

> Error: The CloudFormation template is invalid: ValidationError: Template error: instance of Fn::GetAtt references undefined resource MyLogGroup

Can help me with 1 example?

**Comment by nuskirk** [comment]
@horike37

**Comment by Pigius** [comment]
@nuskirk I found this issue today, so I happy to explain:

this error displays because you do not have such a resource defined, so arn cannot be downloaded.

What you can do is to define with cloudformation a new log group, and then refer to it:

Within the serverless.yml in the resources do:

```yaml
resources:
  Resources:
    YourNameForTheLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 30
```
After this, in your step functions definition add:

```yaml
      loggingConfig:
        level: ERROR
        includeExecutionData: true
        destinations: 
          - !GetAtt YourNameForTheLogGroup.Arn
```

And that's it:
<img width="1324" alt="Screenshot 2022-09-07 at 21 59 01" src="https://user-images.githubusercontent.com/8863200/188966790-5d20808b-31db-4c70-a35c-72562cf5a27f.png">

@nuskirk can you check it, and ping here, so @horike37 could close the issue :)
