### ISSUE TITLE
 Deprecation warning: CLI options definitions were upgraded with "type" property

### ISSUE THREAD

**Issue by spinlud** [serverless-operations/serverless-step-functions#415]
- `serverless`: 2.33.1
- `serverless-step-functions`: 2.29.0

Not sure what is complaining about, anyway reporting here:

![image](https://user-images.githubusercontent.com/12783208/113706587-25253180-96df-11eb-8a42-ca09792026ac.png)

serverless.yml
```yml
frameworkVersion: ^2.33.1
service: my-service
configValidationMode: error
variablesResolutionMode: 20210219

plugins:
  - serverless-step-functions
 
# ...
```
