### ISSUE TITLE
Cloudformation resource reference syntax

### ISSUE THREAD

**Issue by spinlud** [serverless-operations/serverless-step-functions#418]
Could I ask why the syntax `!Ref resourceName` does not work here, instead I have to use `#{resourceName}` syntax to reference a Cloudformation resource defined in the template?

```yml
stepFunctions:
  stateMachines:
    MyStateMachine:
      name: ${env:STACK_NAME}
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [StepFunctionLogGroup, Arn]
      definition:
        StartAt: First
          First:
            Type: Task
            Resource: arn:aws:states:::ecs:runTask.sync
            InputPath: $
            Parameters:
              Cluster: "#{EcsCluster}"
              TaskDefinition: "#{EcsTaskDefinition}"
              LaunchType: FARGATE
              # [...]
```

`"serverless-step-functions": "^2.29.0"`
