### ISSUE TITLE
EventBridge // CloudWatch Event Rules Not Being Created

### ISSUE THREAD

**Issue by lctnstn** [serverless-operations/serverless-step-functions#421]
The service deploys fine but completely ignores/skips over ccreating EventBridge and CloudWatch event rules. 

```
Framework Core: 2.30.3
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.5
```

```
service: sample

frameworkVersion: '2'

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev

functions:
  hello:
    handler: handler.hello

stepFunctions:
  stateMachines:
    sampleMachine:
      events:
        - eventBridge:
          event:
            source:
              - "aws.workspaces"
            detail-type:
              - "AWS API Call via CloudTrail"
            detail:
              eventSource:
                - "workspaces.amazonaws.com"
              EventName:
                - CreateWorkspaces
                - CreateTags
                - DeleteTags
      definition:
        StartAt: HelloWorld
        States:
          HelloWorld:
            Type: Task
            Resource: !GetAtt hello.Arn
            End: true

```
