### ISSUE TITLE
Support for API Gateway WebSocket (WS) invocation

### ISSUE THREAD

**Issue by andyrichardson** [serverless-operations/serverless-step-functions#440]
Hey there - first off, thanks for making this plugin!

# Feature request

State machines currently cannot be not invoked by websocket events

```yml
stepFunctions:
  stateMachines:
    myMachine:
      events:
        - websocket:
            route: $connect
```

> Note: Full reproduction [here](https://github.com/andyrichardson/subscriptionless/blob/838b7c99bcf5280692f45464f4fd3dc37f375d96/example/serverless.yml#L53)

Initially I thought this was a bug (no error during deployment) but it looks like this just isn't supported currently.

Would be nice to have event feature parity with lambda functions :crossed_fingers:
