### ISSUE TITLE
New ${aws:xxx} variables added in serverless 2.50.0 and this plugin breaks packaging / deployment

### ISSUE THREAD

**Issue by herebebogans** [serverless-operations/serverless-step-functions#446]
minimal example to reproduce

```
service:
  name: aws-region-variable-test
plugins:
  - serverless-step-functions
provider:
  name: aws
  region: us-east-1
functions:
  example:
    handler: src/test.handler
    environment:
      AWS_REGION_TEST: ${aws:region}
      AWS_ACCOUNTID_TEST: ${aws:region}
```

```
$ sls package
Serverless Error ----------------------------------------
 
  Invalid variable reference syntax for variable aws:region. You can only reference env vars, options, & files. You can check our docs for more info.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.15.4
     Framework Version:         2.50.0
     Plugin Version:            5.4.3
     SDK Version:               4.2.3
     Components Version:        3.13.3

```

commenting  serverless-step-functions results in packaging or deployment success
