### ISSUE TITLE
Receiving TypeError: Cannot read property 'stepFunctions' of undefined since 3.0.0 release

### ISSUE THREAD

**Issue by dsciacca** [serverless-operations/serverless-step-functions#454]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?  
Since the v3.0.0 release my team is unable to deploy stacks that include the stepFunctions section in the `serverless.yaml` file, seeing `TypeError: Cannot read property 'stepFunctions' of undefined` at least when trying to deploy a new stack that includes a `stepFunctions` section. Pinning to `serverless-step-functions v2.32.0` resolves the issue.
* What did you expect should have happened?  
Expected this to work as usual and stack to be deployed w/o issue. The same `serverless.yaml` files have been working for creating/updating new/existing stacks for years, no changes were made to these files on our end.
* What was the config you used?   
Pertinent section of my `serverless.yaml` file:
```
stepFunctions:
  stateMachines:
    partnerStateMachine:
      name: dxdl_sm-partner_state_machine_${self:provider.stage}
      role: ${file(../../config/env_configs.yaml):${self:provider.stage}.role}
      definition: ${file(../../step_functions/partners/create_partner_sfn.yml):definition}

    deletePartnerStateMachine:
        name: dxdl_sm-delete_partner_state_machine_${self:provider.stage}
        role: ${file(../../config/env_configs.yaml):${self:provider.stage}.role}
        definition: ${file(../../step_functions/partners/delete_partner_sfn.yml):definition}
```
* What stacktrace or error message from your provider did you see?  
```
709 | Type Error ---------------------------------------------
--
710 |  
711 | Cannot read property 'stepFunctions' of undefined
712 |  
713 | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
714 |  
715 | Get Support --------------------------------------------
716 | Docs:          docs.serverless.com
717 | Bugs:          github.com/serverless/serverless/issues
718 | Issues:        forum.serverless.com
719 |  
720 | Your Environment Information ---------------------------
721 | Operating System:          linux
722 | Node Version:              10.1.0
723 | Serverless Version:        1.48.3
724 | Enterprise Plugin Version: 1.3.11
725 | Platform SDK Version:      2.3.2
```

Similar or dependent issues:
* NA AFAIK

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.48.3
* ***The Plugin Version you're using***: 3.0.0
* ***Operating System***: linux
* ***Stack Trace***: 
```
709 | Type Error ---------------------------------------------
--
710 |  
711 | Cannot read property 'stepFunctions' of undefined
712 |  
713 | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
714 |  
715 | Get Support --------------------------------------------
716 | Docs:          docs.serverless.com
717 | Bugs:          github.com/serverless/serverless/issues
718 | Issues:        forum.serverless.com
719 |  
720 | Your Environment Information ---------------------------
721 | Operating System:          linux
722 | Node Version:              10.1.0
723 | Serverless Version:        1.48.3
724 | Enterprise Plugin Version: 1.3.11
725 | Platform SDK Version:      2.3.2
```
* ***Provider Error messages***: `TypeError: Cannot read property 'stepFunctions' of undefined`
