### ISSUE TITLE
${aws:region} AWS specific variable not working on deployment

### ISSUE THREAD

**Issue by rodrigomata** [serverless-operations/serverless-step-functions#460]
# Bug Report

## Description

For bug reports:
* What went wrong?
Trying to use `${aws:region}` for defining a lambda arn fails on deployment, contrary to `${sls:stage}` which works ok.

* What did you expect should have happened?
I thought that with the PR merged [here](https://github.com/serverless-operations/serverless-step-functions/issues/446) the issue would be solved, but I keep getting this error:

```
The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: XXXXXX; Proxy: null).
```

My intention is to be able to use `${aws.region}`.

* What was the config you used?
```
service: sample-service
frameworkVersion: '2'

provider: aws

stepFunctions:
  stateMachines:
    sampleMachine:
      definition:
        StartAt: Initial
        States:
          Initial:
            Type: Task
            Resource: arn:aws:lambda:${aws.region}:${aws.accountId}:function:lambda-name-${sls:stage}
            End: true
```
In the example above, if I change `${aws.region}` for eg. `${self:provider.region}` (by adding this property of course) it works.

* What stacktrace or error message from your provider did you see?
```
The policy failed legacy parsing (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: XXXXXX; Proxy: null).
```

Similar or dependent issues:
* #446
