### ISSUE TITLE
Step Function Plugin outputs HTTP API Endpoints instead of correct REST Endpoints 

### ISSUE THREAD

**Issue by fernando-mc** [serverless-operations/serverless-step-functions#492]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
When deploying HTTP API endpoints while also deploying StepFunctions that trigger from a REST API (because there is currently no HTTP API Support) the StepFunction will reference the incorrect API in the CLI output. Example:

```
✔ Serverless StepFunctions OutPuts
endpoints:
  POST - https://abcd123hud.execute-api.us-west-2.amazonaws.com/send-to-step-function


✔ Service deployed to stack my-stack-dev (111s)

endpoints:
  GET - https://abcd123hud.execute-api.us-west-2.amazonaws.com/stuff
```

* What did you expect should have happened?
The StepFunctions OutPuts endpoint should be different from the Service deployed outputs. For example:
- This: `https://efgh456duh.execute-api.us-west-2.amazonaws.com/dev/send-to-step-function` 
- Instead of this: `https://abcd123hud.execute-api.us-west-2.amazonaws.com/send-to-step-function`

* What was the config you used?

```yaml
service: my-service
frameworkVersion: '3'

configValidationMode: error
deprecationNotificationMode: warn:summary

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  httpApi:
    cors: true
    ... omitted authorizer config

functions:
  sendToLambda: 
    handler: src/handlers/send-to-lambda.send

...omitted

stepFunctions:
  stateMachines:
    sendToStepFunction:
      events:
        - http:
            path: send-to-step-function
            method: POST
            cors: true
      name: sendToStepFunction
      definition:
        Comment: "The state machine used to queue things in the system."
        StartAt: sendToLambda
        States:
          sendToLambda:
            Type: Task
            Resource:
              Fn::GetAtt: [sendToLambda, Arn]
            End: true
```

* What stacktrace or error message from your provider did you see?
None.

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issues:
https://github.com/serverless-operations/serverless-step-functions/issues/215

## Additional Data
* ***Serverless Framework Core Version you're using***: 3
* ***The Plugin Version you're using***:  "serverless-step-functions": "^3.5.1"
* ***Operating System***: OSX
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
