### ISSUE TITLE
Support CloudWatch Custom Alarm name

### ISSUE THREAD

**Issue by lucasvieirasilva** [serverless-operations/serverless-step-functions#494]
# This is a Feature Proposal

## Description

Currently, all alarms created enabled by the serverless step functions plugins do not set the CloudFormation property `AlarmName`, and It will be nice to have a way to set the alarm name template.

Example:
```yaml
service: myservice

plugins:
  - serverless-step-functions

stepFunctions:
  stateMachines:
    main-workflow:
      name: main
      alarms:
        nameTemplate: $[stateMachineName]-$[cloudWatchMetricName]-alarm
        topics:
          alarm: !Ref AwsAlertsGenericAlarmTopicAlarm
        metrics:
          - executionsFailed
          - executionsAborted
          - executionsTimedOut
          - executionThrottled
        treatMissingData: ignore
      definition: ${file(./step-functions/main.asl.yaml)}
```

With the `nameTemplate` property the user has the flexibility to change the alarm name, based on this plugin: https://github.com/ACloudGuru/serverless-plugin-aws-alerts.

Suggestion for supported variables to the `nameTemplate`

- `stateMachineName`
- `metricName`
- `cloudWatchMetricName`

Also, support `alarmName` property directly in the metric object, example:

```yaml
service: myservice

plugins:
  - serverless-step-functions

stepFunctions:
  stateMachines:
    main-workflow:
      name: main
      alarms:
        nameTemplate: $[stateMachineName]-$[cloudWatchMetricName]-alarm
        topics:
          alarm: !Ref AwsAlertsGenericAlarmTopicAlarm
        metrics:
          - metric: executionsFailed
            alarmName: mycustom-name-${self:stage.region}-Failed-alarm
          - executionsAborted
          - executionsTimedOut
          - executionThrottled
        treatMissingData: ignore
      definition: ${file(./step-functions/main.asl.yaml)}
```
