### ISSUE TITLE
Add content filtering to event patterns

### ISSUE THREAD

**Issue by rayniel95** [serverless-operations/serverless-step-functions#513]
# This is a (Feature Proposal)

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Add [content filtering](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html) in the event patterns. This will help us to filter the events using more flexible patterns.

I would like to add filters to the event patterns of my step functions, maybe something like this:
...
```yaml
stepFunctions:
  validate: true
  stateMachines:
    mymachine:
      type: EXPRESS
      id: "${self:custom.state-machine-id}"
      name: ${self:service}-${opt:stage}-state-machine
      events:
        - eventBridge:
            eventBusName: !Ref EventBusName
            event:
              detail:
                appName: 
                  - "myappname"
                eventName: 
                  - prefix: "superevent"
                orderId: 
                  - numeric:
                    - ">"
                    - 0
                    - "<="
                    - 100
      definition:
        ${file(resources/step-functions/definition.yaml)}
```
...
You can take a look to the [events definitions for lambda functions in the serverless documentation](https://www.serverless.com/framework/docs/providers/aws/events/event-bridge#setting-up-event-pattern-matching) to get an idea about my proposal.

## Additional Data
* ***Serverless Framework Core Version you're using***: serverless@3.18.2
* ***The Plugin Version you're using***:
- serverless-python-requirements@5.4.0
- serverless-plugin-tracing@2.0.0
- serverless-tag-resources@1.2.14
- serverless-step-functions@3.7.0
* ***Operating System***: linux
* ***Stack Trace***:
* ***Provider Error messages***:
