### ISSUE TITLE
Redeploying after having made AWS console manual changes does not overwrite manual changes

### ISSUE THREAD

**Issue by bendubuisson** [serverless-operations/serverless-step-functions#526]
# This is a Bug Report

## Description

Updating the time on a `Wait` state manually through the AWS console and redeploying over it. I expect my redeploy to overwrite what I changed manually but it doesn't.

My `serverless.yaml` has:

```
          WaitAndTryAgain:
            Type: Wait
            Seconds: 86400 # 1 day (60*60*24)
            Next: MyLambda
```

I changed it to `120 seconds` manually through the AWS console for testing purposes, redeployed many times and that value stayed at 120 seconds.

## Additional Data
* ***Serverless Framework Core Version you're using***: 3.21.0
* ***The Plugin Version you're using***: 3.8.0
* ***Operating System***: Github Actions (some linux flavour I guess)
