### ISSUE TITLE
 Support to separate step functions states into different yml files

### ISSUE THREAD

**Issue by cwardcode** [serverless-operations/serverless-step-functions#538]
# This is a Feature Proposal

## Description

For feature proposals:
* It is currently possible to create a separate **state machine** (#177) within a different file; however, it would be nice to also allow the possibility to split states into their own files as well, so that users do not have to re-define the same functionality multiple times. It does not seem like the plugin supports a similar approach at the state level, though.

I believe the definition may look something like this:

```YAML
stepFunctions:
  stateMachines:
    mundaneTask:
      name: '${self:provider.stage}-something-repetitive  
      definition:
        Comment: 'Starts a file upload'
        StartAt: repetitiveStep
        States:
          repetitiveStep: ${file(something-repetitive.yml)}
```

Any feedback or help would be appreciated!
