### ISSUE TITLE
Resource name is non alphanumeric.

### ISSUE THREAD

**Issue by cvargas-xbrein** [serverless-operations/serverless-step-functions#583]
# This is a  Bug Report 

## Something was wrong with the underscore character , before this was´t a problem con mi projects  , At moment of deploy a function, the  name by example : mi-stepfunction sls give me a error:
 
Code of my stepfunctions , note thas sf_6 pass perfectly  :

```
  # Before
  sf_6:
    name: workflow_${self:custom.stage}_inputs_estudios_parallelize_buffers
    role: arn:aws:iam::958531303673:role/service-role/StepFunctions-DMSCreateReplicationInstance-role-566d43b8
    definition:
      ${file(./sls_imports/step_functions/06_parallelize_buffers.asl.yaml)}
    tracingConfig:
      enabled: true
# New code  test ok with minus 
  sf_7:
    name: workflow-${self:custom.stage}-bulk-delete-objects-from-s3
    role: arn:aws:iam::958531303673:role/service-role/StepFunctions-DMSCreateReplicationInstance-role-566d43b8
    definition:
      ${file(./sls_imports/step_functions/bulk_delete_objects_from_s3.asl.yaml)}
    tracingConfig:
      enabled: true
# New code  test fail with minus 
  sf_8:
    name: workflow_${self:custom.stage}_inputs_estudios_parallelize_pipeline.asl
    role: arn:aws:iam::958531303673:role/service-role/StepFunctions-DMSCreateReplicationInstance-role-566d43b8
    definition:
      ${file(./sls_imports/step_functions/pipelines/parallelize_pipeline.asl.yaml)}
    tracingConfig:
      enabled: true
```
SLS ERROR : 
```
Error:
The CloudFormation template is invalid: Template format error: Resource name WorkflowUnderscoredevUnderscoreinputsUnderscoreestudiosUnderscoreparallelizeUnderscorepipeline.asl is non alphanumeric.
```

 
## Additional Data
* ***Serverless Framework Core Version you're using***:
      Framework Core: 3.34.0 (local) 3.32.2 (global)
      Plugin: 6.2.3
      SDK: 4.3.2
* ***The Plugin Version you're using***:
      plugins:
        - serverless-python-requirements
        - serverless-prune-plugin
        - serverless-step-functions
* ***Operating System***: W10
* ***Stack Trace***:
* ***Provider Error messages***:

```
Error:
The CloudFormation template is invalid: Template format error: Resource name WorkflowUnderscoredevUnderscoreinputsUnderscoreestudiosUnderscoreparallelizeUnderscorepipeline.asl is non alphanumeric.
```
