### ISSUE TITLE
Invalid type for parameter selectionPattern

### ISSUE THREAD

**Issue by louis0802** [serverless-operations/serverless-step-functions#593]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?  Invalid type for parameter selectionPattern
* What did you expect should have happened? The type should be string instead of int
* What was the config you used?

```
stepFunctions:
  validate: true
  stateMachines: 	
    process:
      name: processStepMachine
      type: EXPRESS
      role:
        Fn::GetAtt: ["ProcessStateMachineRole", "Arn"]
      events:
        - http:
            path: /process
            method: post
            action: StartSyncExecution
            request:
              template:
                application/json: |
                  #set( $body = $util.escapeJavaScript($input.json('$')) )
                  {
                    "input": "$body",
                    "stateMachineArn": "arn:aws:states:${aws:region}:000000000000:stateMachine:processStepMachine"
                  }
      definition:
        StartAt: process
        States:
          process:
            Type: Task
            Resource:
              Fn::GetAtt: [process, Arn]
            End: true  
``` 

* What stacktrace or error message from your provider did you see?
CREATE_FAILED: ApiGatewayMethodProcessPost (AWS::ApiGateway::Method)
Parameter validation failed:
Invalid type for parameter selectionPattern, value: 200, type: <class 'int'>, valid types: <class 'str'>

Similar or dependent issues:
* NA

## Additional Data
* ***Serverless Framework Core Version you're using***:  3.34.0
* ***The Plugin Version you're using***:  3.17.0
* ***Operating System***: MacOS
* ***Stack Trace***:
* ***Provider Error messages***: Invalid type for parameter selectionPattern, value: 200, type: <class 'int'>, valid types: <class 'str'>

I checked the code and found it is defined in int not string. Does anyone face the same issue? Could I create PR for it?
https://github.com/serverless-operations/serverless-step-functions/blob/8772ae7d8662b80bc584342cc39e48fc6f9c6a53/lib/deploy/events/apiGateway/methods.js#L199
