### ISSUE TITLE
Generate policy statements for "Call third-party API" states

### ISSUE THREAD

**Issue by yuyokk** [serverless-operations/serverless-step-functions#599]
# This is a Feature Request

## Description

AWS announced [ability to call external endpoints](https://aws.amazon.com/blogs/aws/external-endpoints-and-testing-of-task-states-now-available-in-aws-step-functions/) at AWS re:invent.

If I define following state:

```yml
Call api:
  Type: Task
  Resource: arn:aws:states:::http:invoke
  Parameters:
    ApiEndpoint.$: '$.apiUrl'
    Method.$: '$.method'
    Authentication:
      ConnectionArn.$: '$.connectionArn'
```

During deploy I see the following warning 

```
Cannot generate IAM policy statement for Task state { Type: 'Task',
  Resource: 'arn:aws:states:::http:invoke',
  Parameters:
   { 'ApiEndpoint.$': '$.apiUrl',
     'Method.$': '$.method',
     Authentication: { 'ConnectionArn.$': '$.connectionArn' } },
  Next: 'Success' }
✓ State machine "SfEventsStepFunction" definition is valid
```

And during run my Step Function fails with 

```
AWS Step Functions is not authorized to perform states:InvokeHTTPEndpoint on API Endpoint https://example.com. Ensure that the StateMachine role contains the states:InvokeHTTPEndpoint permission for the given API Endpoint
```

## Additional Data
* ***Serverless Framework Core Version you're using***: 3.38.0
* ***The Plugin Version you're using***: 3.17.0
