### ISSUE TITLE
I want to specify the waiting time by parameter.

### ISSUE THREAD

**Issue by DogFortune** [serverless-operations/serverless-step-functions#602]
# This is a Question

## Description
I want to adjust the waiting time of a state machine with a parameter, but I am having trouble with a validation error.
A simple structure of a state machine is described here for reference.

```yml:statemachine.yml
name: sample-statemachine
definition:
  StartAt: wait
  States:
    wait:
      Type: Wait
      Seconds: ${param:intervalSeconds}
      Next: status_ok
    status_ok:
      Type: Pass
      End: true
```
The deployment commands are as follows

```shell
npx sls deploy --verbose \
--stage dev \
--param="intervalSeconds=60"
```

command, I get an error.

```
Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: Expected value of type Integer at /States/wait/Seconds'
```

When the "print" command is executed, it is indeed a string where an integer should be.

```yml
    sample:
      name: sample-statemachine
      definition:
        StartAt: wait
        States:
          wait:
            Type: Wait
            Seconds: '60'  # not integer
            Next: status_ok
          status_ok:
            Type: Pass
            End: true
```

It would be very helpful if you could tell me if there is a way to make the command successful.

## Additional Data
***Serverless Framework Core Version you're using***:
serverless v3.38.0

***The Plugin Version you're using***:
- serverless-step-functions v3.19.0
- serverless-prune-plugin v2.0.2
- serverless-python-requirements v6.0.1
- serverless-better-credentials v2.0.0

***Operating System***:
- macOS Monterey v12.6.8
- Node.js v20.11.0
- npm v10.4.0

**Comment by zirkelc** [comment]
Hi,

unfortunately, `params` are always strings. Serverless has helper function to [convert strings to booleans](https://www.serverless.com/framework/docs/guides/variables#read-string-variable-values-as-boolean-values), but it looks like there are no function to convert strings to numbers. I would recommend to open an issue at Serverless directly.

A possible workaorund could be to use JavaScript function resolver to convert the string to number:
https://www.serverless.com/framework/docs/guides/variables/javascript

Not tested, but roughly like:

```js
// params-numbers.js
module.exports = async ({ options, resolveVariable }) => {
  const intervalSeconds = await resolveVariable('param:intervalSeconds');

  return {
    intervalSeconds: Number(intervalSeconds)
  }
}
```

Use it like:

```yaml
name: sample-statemachine
definition:
  StartAt: wait
  States:
    wait:
      Type: Wait
      Seconds: ${file(./params-numbers.js):intervalSeconds}
      Next: status_ok
    status_ok:
      Type: Pass
      End: true
```
