### ISSUE TITLE
State machine Alarm does not support custom period

### ISSUE THREAD

**Issue by nbcchen** [serverless-operations/serverless-step-functions#612]
# This is a (Bug Report / Feature Proposal)
Feature Proposal
## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
Alarm does not support `period`. Adding `period` removes the alarm. Is it possible to add support for custom period config?
* If there is additional config how would it look
```yaml
  metrics:
    - executionsFailed
  treatMissingData: ignore
  period: 36000 # here
```

## Additional Data
* ***Serverless Framework Core Version you're using***:  3.38.0
* ***The Plugin Version you're using***: 1.7.5
* ***Operating System***: Windows
* ***Stack Trace***:
* ***Provider Error messages***:
