### ISSUE TITLE
State machine definition does not support JSONata

### ISSUE THREAD

**Issue by villagoizi** [serverless-operations/serverless-step-functions#637]
### Does not support JSONata
**Description**
In this line of code it expects a state.Parameters but when you use JSONata everything changes from Parameters to Arguments.
https://github.com/serverless-operations/serverless-step-functions/blob/313355ad3dd41e46605e41abdade7faed66f869f/lib/deploy/stepFunctions/compileIamRole.js#L329

You get the following exception when performing an sls deploy:
`TypeError: Cannot read properties of undefined (reading 'FunctionName')`

This is the definition used

```
Comment: Validate
StartAt: input validation
QueryLanguage: JSONata
States:
  input validation:
    Type: Task
    Resource: arn:aws:states:::lambda:invoke
    Output: '{% $states.result.Payload %}'
    Assign:
      command: '{% $merge([$states.input.params.path, $states.input.body]) %}'
      meta: '{% $states.input %}'
    Arguments:
      FunctionName:
        'Fn::GetAtt':
          - ValidatorLambda
          - Arn
      Payload:
        rule: ${file(src/model-config/schemas/update.yml)}
        payload: '{% $merge([$states.input.params.path, $states.input.body]) %}'
    Retry:
      - ErrorEquals:
          - States.ALL
        IntervalSeconds: 1
        MaxAttempts: 2
        BackoffRate: 1
        JitterStrategy: FULL
    End: true
```

**Additional data**
- Serverless Framework Core Version you're using: ^3
- The Plugin Version you're using: ^3.21.1
- Operating System: Linux

**Comment by olivierto** [comment]
+ 1 same issue ! 
Converted a big step function to JSONata in the AWS console... lost 2 days of work to realise that it's not supported :'( 
I will try to make a PR ...

**Comment by zirkelc** [comment]
@villagoizi I have implemented JSONata support in PR https://github.com/serverless-operations/serverless-step-functions/pull/636

It looks like it wasn't released yet, but you can use my preview branch: https://pkg.pr.new/zirkelc/serverless-step-functions@d2555b7

@horike37 when will you release a new version?

**Comment by gson88** [comment]
Hmm I use JSONata in step functions, am I using it wrong?
What is the purpose of making the resource `arn:aws:states:::lambda:invoke` instead of the lambda I want to invoke?

```yaml
StartAt: CloneStuff
QueryLanguage: "JSONata"
States:
  CopySomeTypes:
    Type: Task
    Resource: resourceArn
    Arguments:
      author: "{% $author %}"
      fromNodeId: "{% $fromNodeId %}"
      toNodeId: "{% $toNodeId %}"
    Output:
      output:
        someType: "{% $states.result.body %}"
    End: true
```
