### ISSUE TITLE
API Gateway timeoutInMillis

### ISSUE THREAD

**Issue by danhnguyeen** [serverless-operations/serverless-step-functions#651]
Hello there,
I would like to change the timeout for API Gateway integration. 
In `serverless`, I can  change this by setting the `timeoutInMillis` property in the `apiGateway` configuration. 

```
provider:
  apiGateway:
    timeoutInMillis: 10000 # Default timeout of 10 seconds for all endpoints
functions:
  fetch:
    handler: handler.hello
    events:
      - http:
          path: /posts/{id}
          method: get
  create:
    handler: handler.bye
    events:
      - http:
          path: /posts
          method: post
          timeoutInMillis: 40000 #
```

But it seems this configuration doesn't work with Step Functions. 
In Step Functions, I tried to change like this but it didn't work.

```
name: hello
type: EXPRESS
events:
  - http:
      path: /hello
      method: GET
      cors: true
      action: StartSyncExecution
      timeoutInMillis: 119000
```

Could you please help me on this? Of course, I can change it directly on the API Gateway console. But it’s not a best practice.
Thanks a lot
