### ISSUE TITLE
Handle Output Transformations

### ISSUE THREAD

**Issue by andrewhertog** [serverless-operations/serverless-step-functions#97]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

API Gateway allows users to modify the response body and headers based on content from the response from lambda, or the step functions. In the case of the step functions the output always appears to be:
`{
    "executionArn": "arn:aws:states:us-east-1:111111111111:execution:Name:ID",
    "startDate": epochTimeStamp
}`

I would like to be able to suppress this output and change the http response code to 201 or 204.

**Comment by horike37** [comment]
Thank you for the proposal @andrewhertog :+1: 
Sounds a good idea, but you cannot implement the feature since there is a restriction on AWS end.
The output body is generated automatically on AWS side, so we are not really sure how to customize the response code.

We would love to get any feedback how to implement it :smile:

**Comment by xonstone** [comment]
Perhaps you try like you did with IntegrationRequest? If I add this to the resources this seems to work

```
    ApiGatewayMethodSubscriptionBrandVarPost:
      Properties:
        Integration:
            IntegrationResponses:
              - StatusCode: 200
                SelectionPattern: '[1-5]\d\d'
                ResponseTemplates:
                  application/json: '{"rules":[]}'
```
